# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project_NoA' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project_NoA
  pod 'AWSS3'
  pod 'AWSCognito'
  pod 'AWSDynamoDB'

end

target 'Project_NoA WatchKit App' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Project_NoA WatchKit App

end

target 'Project_NoA WatchKit Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Project_NoA WatchKit Extension
end
